services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017"
      DB_NAME: "userdb"

volumes:
  mongo-data:
