apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      # We can have timeout setting in the api server to wait for these services instead of using initContainers
      #  but retaining this as an example
      # initContainers:
      # - name: wait-for-mongo
      #   image: busybox
      #   command: ['sh', '-c', 'until nc -z mongo.default.svc.cluster.local 27017; do echo waiting for mongo; sleep 2; done;']
      # - name: wait-for-azurite
      #   image: busybox
      #   command: ['sh', '-c', 'until nc -z azurite.default.svc.cluster.local 10000; do echo waiting for mongo; sleep 2; done;']
      containers:
        - name: api
          image: skaffoldapp-api
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_HOST
              value: {{ .Values.global.mongodb.host | quote }}
            - name: MONGODB_PORT
              value: {{ .Values.global.mongodb.port | quote }}
            - name: MONGODB_USERNAME
              value: {{ .Values.global.mongodb.username }}
            - name: MONGODB_PASSWORD  
              value: {{ .Values.global.mongodb.password }}
            - name: AZURE_STORAGE_ACCOUNT
              value: {{ .Values.azure.storage_account }}
            - name: AZURE_STORAGE_KEY
              value: {{ .Values.azure.storage_key }}
            - name: AZURE_STORAGE_BLOB_ENDPOINT
              value: {{ .Values.azure.blob_endpoint }}
            - name: AZURE_STORAGE_CONTAINER_NAME
              value: {{ .Values.azure.container_name }}
