apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
