apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: skaffoldapp
build:
  artifacts:
    - image: my-app
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    # The only resource not using helm
    - k8s/azurite.yaml
    # Retained here to show how to use without helm
    # - k8s/mongodb.yaml
    # - k8s/deployment.yaml
    # - k8s/service.yaml
    # - k8s/ingress.yaml
portForward: 
  - resourceType: service
    resourceName: my-ingress-ingress-nginx-controller
    namespace: kube-system
    port: 80 
    localPort: 8080
deploy:
  helm:
    releases:
      - name: mongodb
        chartPath: k8s/charts/mongodb
        valuesFiles:
          - skaffold-global-values.yaml
      - name: app
        chartPath: k8s/charts/app
        valuesFiles:
          - skaffold-global-values.yaml