apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              value: mongo
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: admin
            - name: MONGODB_PASSWORD  
              value: admin
            - name: AZURE_STORAGE_ACCOUNT
              value: my-storage-account
            - name: AZURE_STORAGE_KEY
              value: my-storage-key
            - name: AZURE_STORAGE_BLOB_ENDPOINT
              value: my-storage-blob-endpoint
            - name: AZURE_STORAGE_CONTAINER_NAME
              value: my-storage-container-name
