replicaCount: 1

image:
  repository: mongo
  tag: "6.0.5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 250m